apiVersion: v1
kind: Service
metadata:
  labels:
    app: mohaned-app
  name: mohaned-app-srvice
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
  selector:
    app: mohaned-app
  type: NodePort