apiVersion: v1
kind: Service
metadata:
  name: mohaned-app-service  # fixed typo
  labels:
    app: mohaned-app
spec:
  type: LoadBalancer  # changed from NodePort to LoadBalancer for external access
  selector:
    app: mohaned-app
  ports:
    - port: 80           # Exposed port on the LoadBalancer
      targetPort: 80     # Port on the Pod your app listens on
      protocol: TCP
